
---
- name: Generate public key
  hosts: localhost
  gather_facts: no
  tasks:
  - name: Create RSA key pair
    shell: ssh-keygen -t rsa -b 2048 -f /root/.ssh/id_rsa -q -N ""
    args:
      creates: /root/.ssh/id_rsa.pub

- name: Add SSH key to all VMs
  hosts: localhost
  gather_facts: no
  vars_prompt:
    - name: "username"
      prompt: "Enter username"
      private: no
    - name: "password"
      prompt: "Enter password"
      private: yes
  vars:
    file_info: "{{ lookup ('file', '/tmp/init/hosts').splitlines() }}"
  tasks:
  - name:  Add SSH key to all VMs
    command: sshpass -p "{{ password }}" ssh-copy-id -i ~/.ssh/id_rsa.pub -o StrictHostKeyChecking=no "{{ item }}"
    with_items: "{{ file_info }}"